### PR TITLE
Tidy setup.py

### PR DESCRIPTION
**Pull request by inverse**
- Specify min Python version (3.6 as prior versions are EOL)
- Tidy description loading

### CODE REVIEW

**Review by FFY00 — APPROVED** [review]
It probably would make sense to move to `setup.cfg`.

**Comment by inverse** [comment]
@FFY00 or adopting Poetry to ease dependency/packaging

**Comment by FFY00** [comment]
It does not support editable installs yet.

**Comment by inverse** [comment]
@FFY00 I get the need for such thing when developing a modular system but would that be a blocker for something like this that is more of a utility package?

**Comment by gaborbernat** [comment]
This has been done in #87

**Pull request closed without merging**
