### PR TITLE
Correct a typo in filelock.py

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Review by hugovk — APPROVED** [review]

**Review by inverse — APPROVED** [review]

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Can you please rebase it on the latest main? You'll need to add some tests for it too, Thanks!

**Comment by jugmac00** [comment]
> Can you please rebase it on the latest main? You'll need to add some tests for it too, Thanks!

I think there are no tests required for a typo-fix within a comment ;-)

**Comment by gaborbernat** [comment]
Indeed 😆 though rebase still needed.

**Comment by gaborbernat** [comment]
Done this in a separate PR :+1: thanks

**Pull request closed without merging**
